# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4642d4edb168472245cadc846a4388737408b5e00c198879b5e3de5286184badd21ac04aa0201264e8a6f0c09f9d04e68c88d4d8c0defd0a5f08c414a469e743

test:
  secret_key_base: cdc04509ec5c96ddbf862c8b46a96d6dc8169f46722c8bb2c5f14b0abcf3c317b36645ecda2db43d10581b44cfab532924cf5940306eb52fb19cde14735fa143

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
